FROM python:3.11-slim

WORKDIR /app

COPY requirements-docker.txt .
RUN pip install --no-cache-dir -r requirements-docker.txt

COPY src/training.py .

ENTRYPOINT ["python", "training.py"]
CMD ["--model", "both"]
